### ISSUE TITLE
File order

### ISSUE THREAD

**Issue by Gouvi** [Ensighten/grunt-spritesmith#105]
I'm spriting my images with the following option:
```
sprite:{
        files: {
            src: 'src/0_0_*.png',
            dest: 'dest/0_0.png',
            destCss: 'sprites.css',
            algorithm: 'top-down'
        },
}
```
I'm spriting together on average 35 images from 0_0_0 -> 0_0_35.png and the sprite generator is not generating them in the correct order. Is there something that I am doing incorrectly or is this not a feature?

**Comment by twolfson** [comment]
We use `sort` in 2 locations:

- `layout` sorting
    - https://github.com/twolfson/layout/blob/2.0.2/lib/algorithms/top-down.algorithm.js#L4
- Sorting by `filename` for consistent builds
    - https://github.com/Ensighten/grunt-spritesmith/blob/3.5.0/src/grunt-spritesmith.js#L118

The JavaScript `.sort` is a lexical comparison, not numeric. Thus, `0 < 1 < 10` but also `10 < 2` because `1 < 2`:

```js
> var arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
undefined
> arr.sort();
[ 0,
  1,
  10,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9 ]
```

To fix your issue, you can zero-pad the sprites (e.g. `00`, `01`):

```js
> var arr = ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10'];
undefined
> arr.sort();
[ '00',
  '01',
  '02',
  '03',
  '04',
  '05',
  '06',
  '07',
  '08',
  '09',
  '10' ]
```

Also, you might need to disable sorting in the `layout` step. This can be done via:

```js
{
  src: '...',
  algorithmOpts: {
    sort: false
  }
}
```

**Comment by Gouvi** [comment]
Thank you!

Much appreciated.
