### ISSUE TITLE
Sprite image filesize larger than sum of individual files

### ISSUE THREAD

**Issue by ryanirilli** [Ensighten/grunt-spritesmith#107]
When I run the task my sprite sheet is 1.1mb but the directory where I keep my sprites is 684K. Is there some configuration I am missing? Thanks for your support.

```
sprite: {
      all: {
        engines: 'canvassmith',
        src: 'src/img/sprites/*.{png,jpg}',
        dest: 'src/img/spritesheet.png',
        destCss: 'src/app/styles/sprites.scss'
      }
}
```

**Comment by twolfson** [comment]
Based on your `src`, it looks like there are some JPGs into your spritesheet. JPG is a lossy image format and usually compresses better. Since the output is PNG which is a lossless format, the size is increasing.

If you take out the JPGs (e.g. put them in a separate spritesheet) and the size is still unsatisfactory, consider adding another `grunt` task to perform image optimization:

https://www.npmjs.com/package/grunt-contrib-imagemin

https://www.npmjs.com/package/grunt-imageoptim

**Comment by ryanirilli** [comment]
great thanks for the info! I'll do that
