### ISSUE TITLE
Generated sprite variables have trailing comma

### ISSUE THREAD

**Issue by tpgmartin** [Ensighten/grunt-spritesmith#161]
Hey there,

Minor issue, but the individual image variables lists in the generated stylesheet - in my case SCSS - always have trailing commas before the closing bracket.

For instance,

```
$img: (0px, 0px, 0px, 0px, 87px, 14px, 122px, 108px, '/sprite.png', 'img', );
```

Cheers

**Comment by twolfson** [comment]
This is expected behavior, the reason is we have lists of unknown length at other points (e.g. `$sprites`) and since we are using Handlebars, we cannot detect when we are at the last element in an `each`. As a result, we have a trailing comma in those locations.

https://github.com/twolfson/spritesheet-templates/blob/10.1.2/lib/templates/scss.template.handlebars#L41

https://github.com/twolfson/spritesheet-templates/blob/10.1.2/test/expected_files/scss.scss#L50

The trailing comma in the posted example is to keep the file consistent with its trailing commas.

**Comment by tpgmartin** [comment]
Thanks for your response, that's good to know

**Comment by davegomez** [comment]
So there's no way to dealing with this?

I can't use Spritesmith with older versions of SASS (the one we have in our prod server).

**Comment by twolfson** [comment]
This can be worked around via:

- Generating CSS content instead of SASS/SCSS content
- Writing/using a custom template

I wasn't aware there was a version of SASS that didn't support this. What's the SASS version?
